name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use Node.js 20

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to use Node.js 20
      with:
        node-version: '20'  # Specify Node.js version 20 explicitly

    - name: Install dependencies
      run: npm install  # Ensure you have a valid package.json file in the repo

    - name: Run tests
      run: npm test  # Make sure you have a test script in your package.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging
      env:
        STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no user@${STAGING_SERVER} 'bash -s' << 'EOF'
        cd /path/to/application  # Navigate to your application directory
        git pull origin main  # Pull the latest code from the 'main' branch
        npm install --production  # Install only production dependencies
        npm run start  # Start the application (replace with your start command)
        EOF
