name: CI/CD Pipeline  # Name of the pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the OS for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to version 3 to use Node.js 20

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to version 3
      with:
        node-version: '20'  # Updated to use Node.js version 20

    - name: Install dependencies
      run: npm install  # Runs the command to install your project's dependencies

    - name: Run tests
      run: npm test  # Runs tests (replace with your test command if different)

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This job runs only after the 'build' job is successful
    if: success()  # Only runs if all previous jobs have succeeded

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to version 3

    - name: Deploy to Staging
      env:
        STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no user@${STAGING_SERVER} 'bash -s' << 'EOF'
        cd /path/to/application  # Navigate to your application directory
        git pull origin main  # Pull the latest code from the 'main' branch
        npm install --production  # Install only production dependencies
        npm run start  # Start the application (replace with your start command)
        EOF
